"""
配置和常量模块

包含数据准备过程中使用的所有配置参数和常量定义
"""

# ADF检验参数
ADF_P_THRESHOLD = 0.05

# 数据处理默认参数
DEFAULT_CONSECUTIVE_NAN_THRESHOLD = 10
DEFAULT_TARGET_FREQ = 'W-FRI'

# 默认列名
DEFAULT_REFERENCE_SHEET_NAME = '指标体系'
DEFAULT_REFERENCE_COLUMN_NAME = '指标名称'
DEFAULT_INDICATOR_COL = '指标名称'
DEFAULT_TYPE_COL = '类型'
DEFAULT_INDUSTRY_COL = '行业'

# 导出的常量
__all__ = [
    'ADF_P_THRESHOLD',
    'DEFAULT_CONSECUTIVE_NAN_THRESHOLD',
    'DEFAULT_TARGET_FREQ',
    'DEFAULT_REFERENCE_SHEET_NAME',
    'DEFAULT_REFERENCE_COLUMN_NAME',
    'DEFAULT_INDICATOR_COL',
    'DEFAULT_TYPE_COL',
    'DEFAULT_INDUSTRY_COL'
]
