"""
配置和常量模块

包含数据准备过程中使用的所有配置参数和常量定义
"""

# 数据处理默认参数
DEFAULT_CONSECUTIVE_NAN_THRESHOLD = 10
DEFAULT_TARGET_FREQ = 'W-FRI'

# 去趋势处理默认参数
DEFAULT_ENABLE_DETREND = False
DEFAULT_MIN_VALID_POINTS_FOR_DETREND = 3

# 默认列名
DEFAULT_REFERENCE_SHEET_NAME = '指标体系'
DEFAULT_REFERENCE_COLUMN_NAME = '指标名称'
DEFAULT_INDICATOR_COL = '指标名称'
DEFAULT_TYPE_COL = '类型'
DEFAULT_INDUSTRY_COL = '行业'

# 导出的常量
__all__ = [
    'DEFAULT_CONSECUTIVE_NAN_THRESHOLD',
    'DEFAULT_TARGET_FREQ',
    'DEFAULT_ENABLE_DETREND',
    'DEFAULT_MIN_VALID_POINTS_FOR_DETREND',
    'DEFAULT_REFERENCE_SHEET_NAME',
    'DEFAULT_REFERENCE_COLUMN_NAME',
    'DEFAULT_INDICATOR_COL',
    'DEFAULT_TYPE_COL',
    'DEFAULT_INDUSTRY_COL'
]
